apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongo  # This is service name for mongodb. In app.py, it is mentioned that it will be accessed by hostname i.e mongo. If we put differnt name here, we will get "Server selection timeout error"
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongo
# Beware of service name for mongodb. We need to give exact name which is mentioned in "app.py" i.e "mongo".
